services:
  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: teste-python
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
      - ./python-service/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - teste

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: teste-backend
    restart: unless-stopped
    expose:
      - "4000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=4000
      - PYTHON_SERVICE_URL=http://python-service:5000
    networks:
      - teste
    depends_on:
      - python-service

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: teste-frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://nginx/api       # âœ… usa caminho relativo
    networks:
      - teste
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: teste-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - python-service
    networks:
      - teste

networks:
  teste:
    driver: bridge
