services:
  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    container_name: invoice-python
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
      - ./python-service/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: invoice-backend
    restart: unless-stopped
    expose:
      - "4000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=4000
      - PYTHON_SERVICE_URL=http://python-service:5000
    networks:
      - app-network
    depends_on:
      - python-service

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: invoice-frontend
    restart: unless-stopped
    expose:
      - "3000"
        # âœ… usa caminho relativo
    networks:
      - app-network
    depends_on:
      - backend

 
networks:
  app-network:
    driver: bridge
